name = "SysModels"
uuid = "a9c7e97e-affa-11e8-2579-d94a0e7341bd"
authors = ["Tristan Caulfield <tristancaulfield@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
